library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity I2C_FSM_tb is
end I2C_FSM_tb;

architecture Behavioral of I2C_FSM_tb is

    -- Component declaration for I2C FSM and Clock Generator
    component I2C_FSM
        port(
            clk      : in  std_logic;
            rst      : in  std_logic;
            wr_enable: in  std_logic;
            sclk     : in  std_logic;
            dclk     : in  std_logic;
            sda      : inout std_logic
        );
    end component;

    component I2C_clock_gen
        port(
            CLK  : in std_logic;
            SCLK : out std_logic;
            DCLK : out std_logic
        );
    end component;

    -- Testbench signals
    signal clk_tb      : std_logic := '0';
    signal rst_tb      : std_logic := '1';
    signal wr_enable_tb: std_logic := '0';
    signal sclk_tb     : std_logic;
    signal dclk_tb     : std_logic;
    signal sda_tb      : std_logic := 'Z';  -- SDA starts high impedance

    -- Clock period
    constant clk_period: time := 10 ns;

begin

    -- Instantiate the clock generator
    U1_clock_gen: I2C_clock_gen
        port map(
            CLK  => clk_tb,     -- System clock
            SCLK => sclk_tb,    -- Generated SCLK
            DCLK => dclk_tb     -- Generated DCLK
        );

    -- Instantiate the I2C FSM
    U2_FSM: I2C_FSM
        port map(
            clk      => clk_tb,     -- System clock for internal use (reset logic)
            rst      => rst_tb,     -- Reset signal
            wr_enable=> wr_enable_tb, -- Write enable
            sclk     => sclk_tb,    -- Slower SCLK generated by clock_gen
            dclk     => dclk_tb,    -- DCLK for SDA transitions
            sda      => sda_tb      -- I2C SDA line
        );

    -- Clock generation process
    clk_process: process
    begin
        while True loop
            clk_tb <= '0';
            wait for clk_period / 2;
            clk_tb <= '1';
            wait for clk_period / 2;
        end loop;
    end process;

    -- Stimulus process
    stimulus: process
    begin
        -- Reset the system
        rst_tb <= '1';
        wr_enable_tb <= '0';
        wait for clk_period * 2;

        -- Release reset and start the write process
        rst_tb <= '0';
        wait for clk_period * 2;

        -- Enable write
        wr_enable_tb <= '1';
        wait for clk_period * 100;  -- Wait for FSM to complete

        -- Disable write after some time
        wr_enable_tb <= '0';

        -- Finish simulation
        wait;
    end process;

end Behavioral;
